### ISSUE TITLE
Stuck on loading images

### ISSUE THREAD

**Issue by JosephBerman** [mikroskeem/radicalaces#9]
I was having a nostalgia moment and remembered this game. I'm trying to run the jar file but it hangs on loading images 50%. Any solutions or ideas how to fix this?

**Comment by JosephBerman** [comment]
Exception in thread "Thread-0" java.lang.RuntimeException: java.lang.IllegalAccessException: class eu.mikroskeem.radicalaces.applet.SimpleAppletContext cannot access class com.sun.media.sound.JavaSoundAudioClip (in module java.desktop) because module java.desktop does not export com.sun.media.sound to unnamed module @43cf184e
        at eu.mikroskeem.radicalaces.applet.SimpleAppletContext.invoke(SimpleAppletContext.java:72)
        at eu.mikroskeem.radicalaces.applet.SimpleAppletContext.lambda$static$1(SimpleAppletContext.java:81)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at eu.mikroskeem.radicalaces.applet.SimpleAppletContext.getAudioClip(SimpleAppletContext.java:24)
        at java.desktop/java.applet.Applet.getAudioClip(Applet.java:346)
        at com.radicalplay.aces.F51.loadsnd(F51.java:358)
        at com.radicalplay.aces.F51.downloadall(F51.java:639)
        at com.radicalplay.aces.F51.run(F51.java:855)
        at java.base/java.lang.Thread.run(Thread.java:833)
        
When running on the command prompt I get this error

**Comment by mikroskeem** [comment]
What Java version?

**Comment by JosephBerman** [comment]
On my windows install it was on java 17, i tried on my linux install and changed to java 8
I could try java 8 on my windows install

**Comment by mikroskeem** [comment]
Try with Java 8 or 11, newer versions are not guaranteed to be supported at the moment.
